### ISSUE TITLE
Translation Dictionary

### ISSUE THREAD

**Issue by Mahmoud217TR** [Syrian-Open-Source/arabic-laravel-docs#21]
Hey there,
While translating to Arabic I noticed that there is some technical words that could be translated in multiple meanings, like:
**"Middleware"** could be translated to **"برمجية وسيطة"** or **"وسيط"** and both have similar meaning but may conflict with each other translations,
like if I use **"برمجية وسيطة"** in some files and another uses **"وسيط"** in his files that may confuse the reader and may not know that they are the same thing.

So I suggest that  we agree on translation dictionary for those words,
Maybe make an online sheet that everyone contributing could see or could add some words or maybe we could add words depending on discussions.

**Comment by dev-dev-15** [comment]
What about keeping the words that are well known in programming world in English ?
Middleware, Route, Parameter, API... all those words every programmer (who speaks any language) know them very well so I think keeping them in English is a good idea.
Maybe adding a description of those words Arabic every time we use theme is also a good idea.
At the end of the day, for someone new to programming, knowing **Middleware** as a **Middleware** is better than knowing it as **وسيط** because he will use it most of the time in English

**Comment by Mahmoud217TR** [comment]
We are doing that by adding the words in English after the translated words like:
 البرمجيات الوسيطة (Middleware)

**Comment by karam-mustafa** [comment]
@0proboy0 
Yes, it is true, and perhaps some personal opinions you prefer, but I would like to mention here that we do not only do literal translation, documentation with all frameworks and programming languages aims to provide content related to the use of a certain technology, so we have to communicate ideas and explanations as well, not just translation

**Comment by karam-mustafa** [comment]
@Mahmoud217TR 
the file  [dictionary.md](https://github.com/Syrian-Open-Source/arabic-laravel-docs/blob/9.x/dictionary.md) has been added, thanks, you can add some terms on it
