### ISSUE TITLE
Public programming terms

### ISSUE THREAD

**Issue by karam-mustafa** [Syrian-Open-Source/arabic-laravel-docs#24]
سنوقم هنا بوضع كافة الكلمات التي سنقوم باعتماد ترجمتها من مثل البرمجيات الوسيطة(middleware)، واقترح ايضاً ان نقوم بوضع شرح بسيط عنها  لتوضيحها باللغة العربية بشكل مبسط.

We will put here all the words that we will adopt translating from such middleware, and I also suggest that we make a simple explanation about them to clarify them in Arabic in a simplified way

**Comment by karam-mustafa** [comment]
duplicated with the same idea in this [issue](https://github.com/Syrian-Open-Source/arabic-laravel-docs/issues/21)

**Comment by Mahmoud217TR** [comment]
**Word or Phrase:** Resolve, Resolving, Resolved

**Translation:** استبيان

**Explanation:** Because resolving an object out of the service container basically means that the service container handles building up the needed dependencies and requirements to hand over an object that is ready to do it’s work.
